app:
  redis:
    enabled: true
    conn: 127.0.0.1:6379
    dbNum: 8
    password: pizafsp2VN
    timeout: 3000
    sentinel:
      enabled: false
      master: bookMaster
      nodes: 127.0.0.1:6379